Port CvButtonSkeleton to Vue3
carbon-design-system/carbon-components-vue pull request #1470
Opened 2023-07-05 20:21 UTC by OlkaB

Contributes to #1469

## What did you do?
Port CvButtonSkeleton to Vue3

## Why did you do it?
Hope this will help to finish transition before Vue2 EOL

## How have you tested it?
please see CvButtonSkeleton.spec.js + CvButtonSkeleton.stories.js
compared behaviours with Vue2 storybook

## Were docs updated if needed?
- [x] Yes

2023-07-11 19:20 UTC, davidnixon requested changes
Wow! Thanks for helping out here! Almost perfect. the only thing I see is that `CvButtonSkeleton` is imported in `index.js` but not exported.  So for me I see nothing in the story and I see this in the console log:
> [Vue warn]: Failed to resolve component: cv-button-skeleton
and a blank story 
![image](https://github.com/carbon-design-system/carbon-components-vue/assets/7536103/9dcd15f1-d7ef-4121-b97a-5ab127257333)



When I add skeleton to the export like:
```js
export {
  CvButton,
  CvButtonConsts,
  CvButtonSet,
  CvIconButton,
  CvButtonSkeleton,
};
```
All works great!
![image](https://github.com/carbon-design-system/carbon-components-vue/assets/7536103/2d480651-d93b-460a-96ee-ee1676990327)


### Extra
For bonus points, since you are in that code anyway, ... could I ask for a separate fix unrelated to skeleton?
The main button stories are in `src/components/CvButton/CvButton.stories.js` but some of them have an issue. The button is blank like this:
![image](https://github.com/carbon-design-system/carbon-components-vue/assets/7536103/3b7d4e61-9bec-43c6-b1ef-8733b0684ff2)

The issue is that somehow we have 
```js
'slotArgs.default': 'Field size',
```
instead of
```js
default: 'Field size',
```

Could you update the button stories to fix that too?

2023-07-12 18:23 UTC, OlkaB commented
> Wow! Thanks for helping out here! Almost perfect. the only thing I see is that `CvButtonSkeleton` is imported in `index.js` but not exported. So for me I see nothing in the story and I see this in the console log:
> 
> > [Vue warn]: Failed to resolve component: cv-button-skeleton
> > and a blank story
> > ![image](https://user-images.githubusercontent.com/7536103/252767716-9dcd15f1-d7ef-4121-b97a-5ab127257333.png)
> 
> When I add skeleton to the export like:
> 
> ```js
> export {
>   CvButton,
>   CvButtonConsts,
>   CvButtonSet,
>   CvIconButton,
>   CvButtonSkeleton,
> };
> ```
> 
> All works great! ![image](https://user-images.githubusercontent.com/7536103/252767945-2d480651-d93b-460a-96ee-ee1676990327.png)
> 
> ### Extra
> For bonus points, since you are in that code anyway, ... could I ask for a separate fix unrelated to skeleton? The main button stories are in `src/components/CvButton/CvButton.stories.js` but some of them have an issue. The button is blank like this: ![image](https://user-images.githubusercontent.com/7536103/252769788-3b7d4e61-9bec-43c6-b1ef-8733b0684ff2.png)
> 
> The issue is that somehow we have
> 
> ```js
> 'slotArgs.default': 'Field size',
> ```
> 
> instead of
> 
> ```js
> default: 'Field size',
> ```
> 
> Could you update the button stories to fix that too?

Thanks @davidnixon . Export added (sorry missed that).
The requested fix for buttons stories will be done in separate PR.

2023-07-15 19:21 UTC, davidnixon commented on src/components/CvButton/__tests__/CvButtonSkeleton.spec.js
> +  test.each([[undefined], [''], ['default']])(
I have not used that `test.each` pattern before. Very cool!

2023-07-15 19:21 UTC, davidnixon approved these changes

2023-07-15 19:21 UTC, merged